field: bb85536d-78ab-4055-ae12-c5a03b27c146
fieldLayouts:
  10d2e5ec-ac17-4622-94fb-562e933eb627:
    tabs:
      -
        elements:
          -
            fieldUid: e7d262b3-d2fc-424e-b22c-9408c1e3fedd
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  e7d262b3-d2fc-424e-b22c-9408c1e3fedd:
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:bb75ac94-87c5-462e-a2aa-81c5ef601282'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:bb75ac94-87c5-462e-a2aa-81c5ef601282'
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:a9087d14-49a1-4d5f-a563-7aaa65e32708'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: image
name: Image
sortOrder: 2
