field: bb85536d-78ab-4055-ae12-c5a03b27c146
fieldLayouts:
  0789c07d-c72b-48e5-99f4-5e3861a40e9f:
    tabs:
      -
        elements:
          -
            fieldUid: c6e47319-c029-4eeb-8d35-bdd4f3983aad
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5504ab1c-b456-40ca-b0fe-6622b2dbe068
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 176b8b50-daa9-47f3-855f-5a9b9d439d45
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a7152ed6-4510-4d96-abf6-37f4f7142ff3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3ed6e66d-1f17-49fb-aec7-44c3c71c0e7e
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: dc80d0b6-3a5d-4aa0-9d1e-42cfb5a6db62
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  176b8b50-daa9-47f3-855f-5a9b9d439d45:
    contentColumnType: text
    fieldGroup: null
    handle: columnOne
    instructions: ''
    name: 'Column one'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  3ed6e66d-1f17-49fb-aec7-44c3c71c0e7e:
    contentColumnType: string
    fieldGroup: null
    handle: columnSize
    instructions: ''
    name: 'Column size'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Half
            -
              - value
              - half
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'One third'
            -
              - value
              - one-third
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Two third'
            -
              - value
              - two-third
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  5504ab1c-b456-40ca-b0fe-6622b2dbe068:
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a7152ed6-4510-4d96-abf6-37f4f7142ff3:
    contentColumnType: text
    fieldGroup: null
    handle: columnTwo
    instructions: ''
    name: 'Column two'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  c6e47319-c029-4eeb-8d35-bdd4f3983aad:
    contentColumnType: string
    fieldGroup: null
    handle: background
    instructions: ''
    name: Background
    searchable: false
    settings:
      allowLimit: false
      allowMultipleSources: false
      allowSelfRelations: false
      branchLimit: ''
      limit: null
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: 'group:83ea4de8-e941-4a39-9b69-76ee7aba4fef'
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Categories
  dc80d0b6-3a5d-4aa0-9d1e-42cfb5a6db62:
    contentColumnType: string
    fieldGroup: null
    handle: textAlign
    instructions: ''
    name: 'Text align'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Left
            -
              - value
              - left
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Center
            -
              - value
              - center
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: text
name: Text
sortOrder: 1
