fieldLayouts:
  cdee655f-d274-4618-b479-ac7cf397c0d9:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
          -
            fieldUid: 413e1433-b8ff-46b3-bfcc-be9117b8fad1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: themeColour
name: 'Theme Colour'
siteSettings:
  47dca4c1-4c2f-452e-ac04-2c6e80e84aa2:
    hasUrls: true
    template: null
    uriFormat: 'theme-colour/{slug}'
structure:
  maxLevels: 1
  uid: c19c0ef1-4d02-44a0-96f2-d2657270e3e2
