contentColumnType: text
fieldGroup: d23e39a0-0ac2-4b8e-bb63-bdd516c460c2
handle: bannerDescription
instructions: ''
name: 'Banner Description'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
