contentColumnType: string(640)
fieldGroup: b8e83cea-d7b0-4a31-bbf7-3f5cf758c4e1
handle: metaDescription
instructions: ''
name: 'Meta description'
searchable: false
settings:
  byteLimit: null
  charLimit: 160
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
