contentColumnType: string(255)
fieldGroup: 77e92724-d234-446b-9ee8-e43841281a22
handle: projectLink
instructions: ''
name: 'Project Link'
searchable: false
settings:
  maxLength: '255'
  placeholder: null
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
