fieldLayouts:
  a93056ce-c0b1-455a-944f-4a4d402f30a1:
    tabs:
      -
        elements:
          -
            fieldUid: 764920db-a701-4822-a9bf-a20ee3bedb2e
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: dd7b40c7-10bf-4eeb-b2be-c806cc49deca
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 841a14f6-0ef1-4c10-97bb-9c6096bd60f2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8ace29d0-c3ea-4050-bdad-d8476ebb005d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 267af4b8-6f69-4df3-a7a2-2896145755ff
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5dba2812-004f-4dbd-9a99-7aca04234886
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: globals
name: Globals
