enableVersioning: true
handle: homepage
name: Homepage
propagationMethod: all
siteSettings:
  47dca4c1-4c2f-452e-ac04-2c6e80e84aa2:
    enabledByDefault: true
    hasUrls: true
    template: pages/homepage
    uriFormat: __home__
type: single
